# 百度翻译 API 信息
baiduTransAppId: baiduTransAppId-xxxxxxxxxxxxxxx
baiduTransAppSecret: baiduTransAppSecret-xxxxxxxxxxxxxxx

# 有道翻译 API 信息, 该配置未启用
youdaoTransAppId: youdaoTransAppId-xxxxxxxxxxxxxxx
youdaoTransSecret: youdaoTransAppSecret-xxxxxxxxxxxxxxx