# 百度翻译 API 信息
baiduTransAppId: baiduTransAppId-xxxxxxxxxxxxxxx
baiduTransAppSecret: baiduTransAppSecret-xxxxxxxxxxxxxxx

# 有道翻译 API 信息, 该配置未启用
youdaoTransAppId: youdaoTransAppId-xxxxxxxxxxxxxxx
youdaoTransSecret: youdaoTransAppSecret-xxxxxxxxxxxxxxx

# 格式化配置
formatannotation: false
formatcarriagereturn: false
formatspace: false

# 翻译接口选择, 默认选择 google 接口
translateSelect: google
# 由于国外 google 无法访问, 我们需要设置 translate.google.com 的镜像, 推荐用 cloudflare worker 实现 js proxy
googleTranslateProxy: google.com